### ISSUE TITLE
you need to update the theme

### ISSUE THREAD

**Issue by speedlorenzo12** [Mixter213/Discord-Themes#11]
the theme is outdated have too much bugs

**Comment by skilledroy** [comment]
i would love to see the bugs fixed as it's my favorite discord theme, but it seems like discord updates have made a mess of it

**Comment by speedlorenzo12** [comment]
arent fixed what do you say

**Comment by Katodo1** [comment]
does the dev still work on it though?

**Comment by Evoley** [comment]
> does the dev still work on it though?

Probably not. Someone could probably create a fork and fix things themselves.

**Comment by Impeta** [comment]
@TonyGamer forked repository has the fixed theme. There's still few issues here and there, but it's in much better updated state. I would've loved to report said issues to her repository, but the issues' tab is closed...

**Comment by AdalynBlack** [comment]
Surprised my fork even got brought up
But yeah, this issue is why I made the fork
That and I wanted to make it automatically switch between dark and light mode with the system theme. It does have some weird random quirks, but I've fixed the major stuff at this point

**Comment by Mixter213** [comment]
hrm, thought i would get notified of issues popping up in my github, guess not. I'm working on an update, as i've finished getting a job, moving, and settled in. ^^

**Comment by AdalynBlack** [comment]
> I would've loved to report said issues to her repository, but the issues' tab is closed...

Didn't realize
I'll open it now

**Comment by Mixter213** [comment]
Just pushed an update, hope you enjoy. also @TonyGamer  i've posted my stylus file if you're still interested in tinkering.
