### ISSUE TITLE
MixPack needs updating after Discord update

### ISSUE THREAD

**Issue by bubbyboytoo** [Mixter213/Discord-Themes#13]
Right now the background image doesn't show up and all the fancy sidebar stuff is broken, this is my favorite theme so I'd really love if you could fix it ASAP please!

**Comment by Mixter213** [comment]
ye, working on a rewrite since it seems a lot of neat things i've added last year are now borked, i'll pass it through the class updater as a temp solution for now.

**Comment by Mixter213** [comment]
Should be updated now.
