### ISSUE TITLE
I cant see the role colors 

### ISSUE THREAD

**Issue by ItzRelampago27** [Mixter213/Discord-Themes#14]
my "rolecolors (the colors in a square a round someone with a role in a server)" dont work i would like to know how to fix it pls, admins are supposed to be blue around, the one ⬇️ is supposed to be like the one in down there
![image](https://github.com/user-attachments/assets/0234b2ab-e099-414f-b876-3c2a98f883bf)
![image](https://github.com/user-attachments/assets/f1da7193-9eb0-40f8-808b-411171c48f2d)

**Comment by Mixter213** [comment]
Discord updated their classes again, should be good now. ^^
