### ISSUE TITLE
Once applied...Good luck trying to get rid of it

### ISSUE THREAD

**Issue by therealOri** [Mixter213/Discord-Themes#3]
Applied it and everytime I tried to acces my user settings, The little winow thing would close making it next to impossibe to do anything in DMs. So I tried to uninstall Bandaged BD then re install it..that didn't fix it and by sheer luck I managed to access my user settings and remove it...took me a long time.

**Comment by giannauwu** [comment]
same thing is happening to me, wish there was a shortcut for user settings so i wouldn't have to go through this problem. still trying to get rid of the theme, wish me luck

**Comment by migsor3r13rwetf** [comment]
How were you able to access your settings?

**Comment by Zayfir** [comment]
I have a touchscreen laptop, that's the only reason I was able to open User settings and get rid of it.

**Comment by Zayfir** [comment]
I found a solution; https://betterdiscord.net/ghdl?id=2515
Just Drag this from your folder to "Themes" and enable it from your user settings. This will only work if you haven't downloaded and enabled the "Chilled Cyan" theme. I have yet to find a solution for that, hope this helps in the meantime

**Comment by tlrossner** [comment]
Closed discord, went to %AppData%\Roaming\BetterDiscord\themes and deleted it, re-opened discord, theme was gone.
