### ISSUE TITLE
Font question?

### ISSUE THREAD

**Issue by lex1903** [Mixter213/Discord-Themes#8]
Hi there, not really an issue, just a query. Is it possible for me to add a line which would allow me to set the font to something? In another theme I use it was possible to edit this bit, which appears immediately below the `@import url` ... tried it on this one but no changes registered.

```
:root {
  /* GENERAL */
  --main-font: Whitney, Helvetica Neue, Helvetica, Arial, sans-serif; /* main font for app (font must be installed) [default: Whitney, Helvetica Neue, Helvetica, Arial, sans-serif] */
  --code-font: Consolas, Liberation Mono, Menlo, Courier, monospace; 
}
```

Thank you!

**Comment by JohnDBumann** [comment]
Hey! Have you found how to do this yet or no?

**Comment by lex1903** [comment]
Nope -- been using the Google fonts plugin as a workaround...

**Comment by Mixter213** [comment]
here is a snippet i found in better discord's discord.
```
/* 
 * Custom Fonts
 * To add a font, either install the font on your computer through the TTF file,
 * or @import a font from http://fonts.google.com/
 */
:root {
    --font: 'Comic Sans MS';
}

::placeholder, body, button, input, select, textarea {
    font-family: var(--font), sans-serif;
}
```
