### ISSUE TITLE
bugs in the  forums 

### ISSUE THREAD

**Issue by speedlorenzo12** [Mixter213/Discord-Themes#9]
when he goes to a forum (eg betterdiscord known issues) and follows one he puts the followed forum in the wrong way like the schreenshot below
![Screenshot (38 1)](https://user-images.githubusercontent.com/111771663/207878000-0d965237-b4b0-4beb-a881-8199a6503e5f.png)

**Comment by Mixter213** [comment]
Will work on that with the update im working on.

**Comment by Mixter213** [comment]
All fixed and good to go
